### ISSUE TITLE
system("clear") doesn't work on windows command prompt.

### ISSUE THREAD

**Issue by chandan00761** [iamnihal/C_Cryptography#1]

**Comment by iamnihal** [comment]
Thanks for raising this issue.
Yeah, system("clear") doesn't work on windows platform.
You can use system("cls"), cls is a valid windows command to clear terminal in windows.
Try it out and let me know if it works or not!! :)

**Comment by chandan00761** [comment]
Use this instead:-
```
#if (defined(_WIN32) || defined(__CYGWIN__))
	#define PLATFORM  "WINDOWS"
#else 
	#define PLATFORM  "LINUX"
#endif
int cleaner()								//Terminal Cleaning
{
	if (PLATFORM == "LINUX")
		system("clear");
	else 
		system("cls");
	return 0;
}
```

**Comment by iamnihal** [comment]
Cool!!
I saw this concept in some forum. This code is kind of portable.
Thanks man. ;)
